- name: creating catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling and enabling nodejs
    ansible.builtin.shell: "{{item}}"
    loop:
      - dnf module disable nodejs -y
      - dnf module enable nodejs:20 -y
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed    
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc!=0
    ansible.builtin.user:
     name: roboshop   
  - name: checking app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: output
  - name: printing output
    ansible.builtin.debug:
      msg: "{{output}}"      