- name: creating catalogue
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling and enabling nodejs
    ansible.builtin.shell: "{{item}}"
    loop:
      - dnf module disable nodejs -y
      - dnf module enable nodejs:20 -y
  - name: installing nodejs
    ansible.builtin.yum:
      name: nodejs
      state: installed    
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc!=0
    ansible.builtin.user:
     name: roboshop   
  - name: checking app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: output
  - name: printing output
    ansible.builtin.debug:
      msg: "{{output}}"      
  - name: Create a /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == false  
  - name: Download catalogue.zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp/catalogue.zip
  - name: Unarchive catalogue.zip in app directory
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes  
  - name: installing dependencies
    ansible.builtin.shell: npm install
  - name: Copy catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: starting and enabling catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes     

       

