- name: creating dispatch
  hosts: dispatch
  become: yes
  tasks:
  - name: installing golang
    ansible.builtin.yum:
      name: golang
      state: installed    
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc!=0
    ansible.builtin.user:
     name: roboshop   
  - name: checking app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: output
  - name: printing output
    ansible.builtin.debug:
      msg: "{{output}}"      
  - name: Create a /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == false  
  - name: Download dispatch.zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/dispatch.zip
      dest: /tmp/dispatch.zip
  - name: Unarchive dispatch.zip in app directory
    ansible.builtin.unarchive:
      src: /tmp/dispatch.zip
      dest: /app
      remote_src: yes  
  - name: installing dependencies
    ansible.builtin.shell: "{{item}}"
    loop:
      - go mod init dispatch
      - go get 
      - go build
    args:
      chdir: /app

  - name: Copy dispatch.service
    ansible.builtin.copy:
      src: dispatch.service
      dest: /etc/systemd/system/dispatch.service
  - name: daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: starting and enabling dispatch
    ansible.builtin.service:
      name: dispatch
      state: started
      enabled: yes   
  
