- name: creating mysql component
  hosts: mysql
  become: yes
  tasks:
  - name: installing mysql server
    ansible.builtin.yum:
      name: mysql-server
      state: installed
  - name: starting and enabling mysql
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: changing defauult root password
    ansible.builtin.shell: mysql_secure_installation --set-root-pass RoboShop@1    
          