- name: creating rabbitmq
  hosts: rabbitmq
  become: yes
  tasks:
  - name: congiguring rabbitmq
    ansible.builtin.shell: "{{item}}"
    loop:
      - curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash
      - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash
  - name: installing rabbitmq
    ansible.builtin.dnf:
      name: rabbitmq-server
      state: installed 
  - name: starting and enabling rabbitmq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes  
  - name: changing rabbitmq password
    ansible.builtin.shell: "{{item}}"
    loop: 
      - rabbitmqctl add_user roboshop roboshop123
      - rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"         
