- name: creating shipping
  hosts: shipping
  become: yes
  tasks:
  - name: installing maven
    ansible.builtin.dnf:
      name: maven
      state: installed    
  - name: checking user
    ansible.builtin.command: id roboshop
    register: out
    ignore_errors: true
  - name: Add the user 'roboshop' after validating
    when: out.rc!=0
    ansible.builtin.user:
     name: roboshop   
  - name: checking app directory exists or not
    ansible.builtin.stat:
      path: /app
    register: output
  - name: printing output
    ansible.builtin.debug:
      msg: "{{output}}"      
  - name: Create a /app directory
    ansible.builtin.file:
      path: /app
      state: directory
    when: output.stat.exists == false  
  - name: Download shipping.zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp/shipping.zip
  - name: Unarchive shipping.zip in app directory
    ansible.builtin.unarchive:
      src: /tmp/shipping.zip
      dest: /app
      remote_src: yes  
  - name: installing dependencies
    ansible.builtin.shell: mvn clean package
    args:
      chdir: /app
  - name: renaming jar
    ansible.builtin.shell: mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /app    


  - name: Copy shipping.service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  - name: daemon-reload 
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: starting and enabling shipping
    ansible.builtin.service:
      name: shipping
      state: started
      enabled: yes   
  - name: installing maven
    ansible.builtin.dnf:
      name: mysql
      state: installed      
  - name: loading schemas
    ansible.builtin.shell: "{{item}}"
    loop:
      - mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/schema.sql
      - mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/app-user.sql
      - mysql -h mysql.joindevops.store -uroot -pRoboShop@1 < /app/db/master-data.sql 
  - name: restarting shipping
    ansible.builtin.service:
      name: shipping
      state: restarted


  
